### ISSUE TITLE
File name

### ISSUE THREAD

**Issue by tangd** [mMrBun/Chat2BI#1]
Hello, I found a correction needed in your project's README.md file. In the file, it says "pip install -r requirements.txt", but the actual file name in the repository is "requirtments.txt".

**Comment by mMrBun** [comment]
> Hello, I found a correction needed in your project's README.md file. In the file, it says "pip install -r requirements.txt", but the actual file name in the repository is "requirtments.txt".

Thank you for pointing this issue. I'll fix it

**Comment by tangd** [comment]
Hi,there are few corrections in README.md.

**Please** put the retrieval model in the retriever/retriever_model directory.

**conda** activate Chat2BI

**Comment by mMrBun** [comment]
> Hi,there are few corrections in README.md.
> 
> **Please** put the retrieval model in the retriever/retriever_model directory.
> 
> **conda** activate Chat2BI

Thank you for pointing out the mistake; I will fix it.
