### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by 2576591129** [mMrBun/Chat2BI#10]
functions/retrieval/G1/corpus.tsv
functions/toolenv/tools
这两个文件缺失，您方便上传一下嘛

**Comment by 2576591129** [comment]
[ToolBench/Training Retriever](https://github.com/OpenBMB/ToolBench?tab=readme-ov-file#training-retriever)
在这里面能找到

**Comment by mMrBun** [comment]
@2576591129 
#8
