### ISSUE TITLE
retriever/retriever_model not found

### ISSUE THREAD

**Issue by liushaoqian** [mMrBun/Chat2BI#11]
raise ValueError("Path {} not found".format(model_name_or_path))
ValueError: Path /home/workstation/liushaoqian/Chat2BI-master/retriever/retriever_model not found

**Comment by mMrBun** [comment]
@liushaoqian 
Place the retrieval model in the retriever/retriever_model directory.
You can download model from huggingface or modelscope. links: [🤗HuggingFace](https://huggingface.co/MrBun/ToolRetrieval_IR_bert_based_chinese)  / [ModelScope](https://modelscope.cn/models/mrsteamedbun/ToolRetrieval_IR_bert_based_chinese/summary)
tree struct:
├── README.md
├── requirements.txt
├── retriever
│   ├── build_retriever.py
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── build_retriever.cpython-310.pyc
│   │   ├── __init__.cpython-310.pyc
│   │   └── utils.cpython-310.pyc
│   ├── retriever_model
│   │   ├── 1_Pooling
│   │   │   └── config.json
│   │   ├── config.json
│   │   ├── config_sentence_transformers.json
│   │   ├── eval
│   │   ├── modules.json
│   │   ├── pytorch_model.bin
│   │   ├── README.md
│   │   ├── sentence_bert_config.json
│   │   ├── special_tokens_map.json
│   │   ├── tokenizer_config.json
│   │   ├── tokenizer.json
│   │   └── vocab.txt
│   └── utils.py

**Comment by liushaoqian** [comment]
我试试，谢谢哈，因为不知道这个retriever是啥意思，明明在model_config已经进行了配置

**Comment by liushaoqian** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/workstation/liushaoqian/Chat2BI-master/functions/retrieval/G1/corpus.tsv'
Traceback (most recent call last):

**Comment by liushaoqian** [comment]
> @liushaoqian Place the retrieval model in the retriever/retriever_model directory. You can download model from huggingface or modelscope. links: [🤗HuggingFace](https://huggingface.co/MrBun/ToolRetrieval_IR_bert_based_chinese) / [ModelScope](https://modelscope.cn/models/mrsteamedbun/ToolRetrieval_IR_bert_based_chinese/summary) tree struct: ├── README.md ├── requirements.txt ├── retriever │   ├── build_retriever.py │   ├── **init**.py │   ├── **pycache** │   │   ├── build_retriever.cpython-310.pyc │   │   ├── **init**.cpython-310.pyc │   │   └── utils.cpython-310.pyc │   ├── retriever_model │   │   ├── 1_Pooling │   │   │   └── config.json │   │   ├── config.json │   │   ├── config_sentence_transformers.json │   │   ├── eval │   │   ├── modules.json │   │   ├── pytorch_model.bin │   │   ├── README.md │   │   ├── sentence_bert_config.json │   │   ├── special_tokens_map.json │   │   ├── tokenizer_config.json │   │   ├── tokenizer.json │   │   └── vocab.txt │   └── utils.py

FileNotFoundError: [Errno 2] No such file or directory: '/home/workstation/liushaoqian/Chat2BI-master/functions/retrieval/G1/corpus.tsv'
Traceback (most recent call last):，按照你的格式把embeding model加入之后，报上面的错

**Comment by mMrBun** [comment]
@liushaoqian 
#8
