### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/workstation/liushaoqian/Chat2BI-master/functions/retrieval/G1/corpus.tsv'

### ISSUE THREAD

**Issue by liushaoqian** [mMrBun/Chat2BI#18]
FileNotFoundError: [Errno 2] No such file or directory: '/home/workstation/liushaoqian/Chat2BI-master/functions/retrieval/G1/corpus.tsv'，这个文件是个啥呀

**Comment by mMrBun** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/home/workstation/liushaoqian/Chat2BI-master/functions/retrieval/G1/corpus.tsv'，这个文件是个啥呀

请先构建工具再使用
