### ISSUE TITLE
请问可以支持调用本地模型吗？

### ISSUE THREAD

**Issue by Teryua** [mMrBun/Chat2BI#23]
现在给地址是默认去hf或者modelscope下载权重，请问怎么样给本地地址就能用vllm推理起来？

**Comment by mMrBun** [comment]
@Teryua 
请查看[README](https://github.com/mMrBun/AIPC?tab=readme-ov-file#api-service)中的介绍，模型路径可以写本地路径

**Comment by Teryua** [comment]
@mMrBun 但是我用了本地地址以后，报错requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/MrBun/ToolRetrieval_IR_bert_based_chinese (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff74f4d190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: ee7db6c3-c0a9-4503-99ec-3ac5a6704c1b)')
应该是在联网下载权重
