### ISSUE TITLE
输入本地模型地址跑不起来

### ISSUE THREAD

**Issue by Teryua** [mMrBun/Chat2BI#24]
python api_demo.py \
--model_name_or_path /home/dev2/model_file/qwen2_32b_chat \
--template default \
--infer_backend vllm
报错
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/MrBun/ToolRetrieval_IR_bert_based_chinese (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6710c7e1d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: f0756f10-216a-4fd3-8e06-eae1c2470c21)')

**Comment by mMrBun** [comment]
检索模型在README中有下载地址，请将模型下载到本地。

**Comment by mMrBun** [comment]
@Teryua 请耐心阅读README
