### ISSUE TITLE
想问下这个报错为啥出现？

### ISSUE THREAD

**Issue by Teryua** [mMrBun/Chat2BI#25]
ImportError: cannot import name 'MixtralBLockSparseTop2MLP' from 'transformers.models.mixtral.modeling_mixtral' 
这个类MixtralBLockSparseTop2MLP明明源码里面有的

**Comment by mMrBun** [comment]
Mixtral模型是最新的吗？

**Comment by Teryua** [comment]
@mMrBun 我没用Mixtral模型，这个是导入transformer包出错的问题。项目里面这行代码from transformers.models.mixtral.modeling_mixtral import MixtralBLockSparseTop2MLP, MixtralSparseMoeBlock报错，但是transformer是有MixtralBLockSparseTop2MLP这个类的

**Comment by Teryua** [comment]
@mMrBun 解决了
