### ISSUE TITLE
修改ECHARTS_PROMPT模板

### ISSUE THREAD

**Issue by bravelll** [mMrBun/Chat2BI#5]
ECHARTS_PROMPT = """
请根据给定的JSON Schema示例和API返回的数据，将其转化为以下示例中的一个。
柱状图JSON Schema示例：
{{
  "chart_type": "bar",
  "data": {{
    "categories": ["category1", "category2", "category3"],
    "series": [
      {{
        "name": "商家A",
        "data": [value1, value2, value3]
      }}
    ]
  }}
}}
饼图JSON Schema示例：
{{
  "chart_type": "pie",
  "data": {{
    "series": [
      {{"name": "category1", "value": value1}},
      {{"name": "category2", "value": value2}},
      {{"name": "category3", "value": value3}}
    ]
  }}
}}
折线图JSON Schema示例：
{{
  "chart_type": "line",
  "data": {{
    "categories": ["category1", "category2", "category3"],
    "series": [
      {{
        "name": "商家A",
        "data": [value1, value2, value3]
      }}
    ]
  }}
}}
API返回的数据：
{observation}
请将上述API返回的数据转换为适合柱状图的JSON数据。
"""

**Comment by mMrBun** [comment]
@bravelll 
这个提示词过于简陋，会在下周前进行优化

**Comment by mMrBun** [comment]
@bravelll 请更新代码
