### ISSUE TITLE
能解释一下你的搜索模型是如何训练的吗？

### ISSUE THREAD

**Issue by bravelll** [mMrBun/Chat2BI#7]

**Comment by mMrBun** [comment]
@bravelll 请参考[ToolBench](https://github.com/OpenBMB/ToolBench?tab=readme-ov-file#training-retriever)
ToolBench用的bert-based，数据也是英文数据，我这里用的是bert-based-chinese，数据是国内的中文api数据

**Comment by bravelll** [comment]
> @bravelll 请参考[ToolBench](https://github.com/OpenBMB/ToolBench?tab=readme-ov-file#training-retriever) ToolBench用的bert-based，数据也是英文数据，我这里用的是bert-based-chinese，数据是国内的中文api数据

你训练的数据能发一下吗？

**Comment by mMrBun** [comment]
@bravelll 如果你是要数据格式的话可以参考ToolBench开源的数据集

**Comment by bravelll** [comment]
> @bravelll 如果你是要数据格式的话可以参考ToolBench开源的数据集

为啥要训练一个embeding模型呢？为了更准确吗？用现成的m3e或者啥不行吗？

**Comment by mMrBun** [comment]
@bravelll 首先，bert和embedding是两种不同的模型，处理的任务也不同，embedding主要负责将文本数据映射到低维向量空间，它是上下文无关的。
