### ISSUE TITLE
WSL运行报错FileNotFoundError

### ISSUE THREAD

**Issue by leeyis** [mMrBun/Chat2BI#8]
WSL运行起来后页面操作报错，看后台报
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/code/Chat2BI/functions/retrieval/G1/corpus.tsv'

请问是否是代码提漏了呀，functions文件夹都不存在

**Comment by mMrBun** [comment]
@leeyis 请先构建工具，在web_demo的json builder中填写自己的api信息，执行之后会自动创建api相关目录和文件

**Comment by liushaoqian** [comment]
> @leeyis 请先构建工具，在web_demo的json builder中填写自己的api信息，执行之后会自动创建api相关目录和文件
web_demo中哪有什么json builder啊

**Comment by mMrBun** [comment]
@liushaoqian 
```python
demo = gr.TabbedInterface(
    [text_analysis_interface, json_interface],
    ["Text Analysis", "JSON Builder"]
)
```
在gradio的第二个table里，两个table是两个不同的功能，或者你可以使用api服务，请参考项目api_demo.py
