### ISSUE TITLE
个人财务相关api的发布和URL地址

### ISSUE THREAD

**Issue by zhangjiekui** [mMrBun/Chat2BI#9]
使用个人财务api和qwen模型。
这是使用个人财务api.json数据：
``
{
    "tool_description": "个人财务相关api",
    "tool_name": "个人财务api",
    "title": "个人财务api",
    "api_list": [
        {
            "name": "get_annual_bill",
            "url": "http://127.0.0.1",
            "description": "获取个人支付宝年度账单",
            "method": "GET",
            "required_parameters": [
                {
                    "name": "year",
                    "type": "string",
                    "description": "年份 e.g. 2022, 2023",
                    "default": "2023"
                }
            ],
            "optional_parameters": [],
            "test_endpoint": {
                "1月": 569.23,
                "2月": 460.74,
                "3月": 541.36,
                "4月": 682.78,
                "5月": 159.35,
                "6月": 357.12,
                "7月": 852.46,
                "8月": 741.32,
                "9月": 369.54,
                "10月": 523.98,
                "11月": 412.69,
                "12月": 785.95
            }
        }
    ],
    "standardized_name": ""
}
“
请问里面的 "url": "http://127.0.0.1"    
该怎么填写呢？这个接口又是怎么发布为服务端的呢？

**Comment by mMrBun** [comment]
@zhangjiekui 这个是api地址，例如我有一个财务类的项目，一共有十几个接口，每个接口肯定有请求地址、请求方式、参数、校验等等信息，这里的url就是接口的请求地址，这个是需要自己维护的。

**Comment by zhangjiekui** [comment]
谢谢。我以为会支持在本项目中写的接口直接发布为后端服务
